### ISSUE TITLE
Androidで動作が不安定

### ISSUE THREAD

**Issue by huideyeren** [huideyeren/ITStudySearch#3]
# 概要

Androidで動作が不安定になる

# 発生機種

Fujitsu F-06E Docomo

# 詳細

以下の例外が発生

```
Android.Content.Res.Resources+NotFoundException: Resource ID #0x7f020001
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/4009/f3074d2c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143
  at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00085] in /Users/builder/data/lanes/4009/9578cdcd/source/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:11283
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00031] in /Users/builder/data/lanes/4009/9578cdcd/source/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:350
  at Android.Content.Res.Resources.GetDrawable (System.Int32 id) [0x00017] in /Users/builder/data/lanes/4009/9578cdcd/source/monodroid/src/Mono.Android/platforms/android-25/src/generated/Android.Content.Res.Resources.cs:744
  at Xamarin.Forms.Platform.Android.ResourceManager.GetDrawable (Android.Content.Res.Resources resource, System.String name) [0x0001c] in <68b107f78d0741228daab0e696a5c326>:0
  at Xamarin.Forms.Platform.Android.Platform.PrepareMenu (Android.Views.IMenu menu) [0x000ec] in <68b107f78d0741228daab0e696a5c326>:0
  at Xamarin.Forms.Platform.Android.FormsApplicationActivity.OnPrepareOptionsMenu (Android.Views.IMenu menu) [0x00000] in <68b107f78d0741228daab0e696a5c326>:0
  at Android.App.Activity.n_OnPrepareOptionsMenu_Landroid_view_Menu_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_menu) [0x00011] in /Users/builder/data/lanes/4009/9578cdcd/source/monodroid/src/Mono.Android/platforms/android-25/src/generated/Android.App.Activity.cs:3866
  at at (wrapper dynamic-method) System.Object:e18fc4d2-5606-4fa7-a492-ea6558bf36da (intptr,intptr,intptr)
  at android.content.res.Resources$NotFoundException: Resource ID #0x7f020001
  at at android.content.res.Resources.getValue(Resources.java:1014)
  at at android.content.res.Resources.getDrawable(Resources.java:659)
  at at md5282f1122c1313907b9bf274dd2c2f344.FormsApplicationActivity.n_onPrepareOptionsMenu(Native Method)
  at at md5282f1122c1313907b9bf274dd2c2f344.FormsApplicationActivity.onPrepareOptionsMenu(FormsApplicationActivity.java:111)
  at at android.app.Activity.onPreparePanel(Activity.java:2508)
  at at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:510)
  at at com.android.internal.policy.impl.PhoneWindow.doInvalidatePanelMenu(PhoneWindow.java:861)
  at at com.android.internal.policy.impl.PhoneWindow$1.run(PhoneWindow.java:263)
  at at android.os.Handler.handleCallback(Handler.java:725)
  at at android.os.Handler.dispatchMessage(Handler.java:92)
  at at android.os.Looper.loop(Looper.java:137)
  at at android.app.ActivityThread.main(ActivityThread.java:5158)
  at at java.lang.reflect.Method.invokeNative(Native Method)
  at at java.lang.reflect.Method.invoke(Method.java:511)
  at at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
  at at dalvik.system.NativeStart.main(Native Method)
```

**Comment by huideyeren** [comment]
まだエラーが出る。
```
Android.Content.Res.Resources+NotFoundException: Resource ID #0x7f020001
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/4009/f3074d2c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143
  at Java.Interop.JniEnvironment+InstanceMethods.CallObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00085] in /Users/builder/data/lanes/4009/9578cdcd/source/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:11283
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00031] in /Users/builder/data/lanes/4009/9578cdcd/source/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:350
  at Android.Content.Res.Resources.GetDrawable (System.Int32 id) [0x00017] in /Users/builder/data/lanes/4009/9578cdcd/source/monodroid/src/Mono.Android/platforms/android-25/src/generated/Android.Content.Res.Resources.cs:744
  at Xamarin.Forms.Platform.Android.ResourceManager.GetDrawable (Android.Content.Res.Resources resource, System.String name) [0x0001c] in <68b107f78d0741228daab0e696a5c326>:0
  at Xamarin.Forms.Platform.Android.Platform.PrepareMenu (Android.Views.IMenu menu) [0x000ec] in <68b107f78d0741228daab0e696a5c326>:0
  at Xamarin.Forms.Platform.Android.FormsApplicationActivity.OnPrepareOptionsMenu (Android.Views.IMenu menu) [0x00000] in <68b107f78d0741228daab0e696a5c326>:0
  at Android.App.Activity.n_OnPrepareOptionsMenu_Landroid_view_Menu_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_menu) [0x00011] in /Users/builder/data/lanes/4009/9578cdcd/source/monodroid/src/Mono.Android/platforms/android-25/src/generated/Android.App.Activity.cs:3866
  at at (wrapper dynamic-method) System.Object:06e156ae-5b47-4457-992e-2ae755acfc6e (intptr,intptr,intptr)
  at android.content.res.Resources$NotFoundException: Resource ID #0x7f020001
  at at android.content.res.Resources.getValue(Resources.java:1014)
  at at android.content.res.Resources.getDrawable(Resources.java:659)
  at at md5282f1122c1313907b9bf274dd2c2f344.FormsApplicationActivity.n_onPrepareOptionsMenu(Native Method)
  at at md5282f1122c1313907b9bf274dd2c2f344.FormsApplicationActivity.onPrepareOptionsMenu(FormsApplicationActivity.java:111)
  at at android.app.Activity.onPreparePanel(Activity.java:2508)
  at at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:510)
  at at com.android.internal.policy.impl.PhoneWindow.doInvalidatePanelMenu(PhoneWindow.java:861)
  at at com.android.internal.policy.impl.PhoneWindow$1.run(PhoneWindow.java:263)
  at at android.os.Handler.handleCallback(Handler.java:725)
  at at android.os.Handler.dispatchMessage(Handler.java:92)
  at at android.os.Looper.loop(Looper.java:137)
  at at android.app.ActivityThread.main(ActivityThread.java:5158)
  at at java.lang.reflect.Method.invokeNative(Native Method)
  at at java.lang.reflect.Method.invoke(Method.java:511)
  at at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
  at at dalvik.system.NativeStart.main(Native Method)
```
